//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _ECLO_STM32F4_H_
#define _ECLO_STM32F4_H_

#include <TinyCLR_Interop.h>
struct Library_Eclo_STM32F4_Eclo_STM32F4_BackupRegisters
{
    TINYCLR_NATIVE_DECLARE(Native_BackupRegister_WriteRegister___STATIC__VOID__U1__I4);
    TINYCLR_NATIVE_DECLARE(Native_BackupRegister_ReadRegister___STATIC__VOID__U1__BYREF_I4);

    //--//

};

struct Library_Eclo_STM32F4_Eclo_STM32F4_RTC
{
    TINYCLR_NATIVE_DECLARE(Native_RTC_Init___STATIC__VOID__U1__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Native_RTC_GetDateTime___STATIC__VOID__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1);
    TINYCLR_NATIVE_DECLARE(Native_RTC_SetDateTime___STATIC__VOID__U1__U1__U1__U1__U1__U1__U1);
    TINYCLR_NATIVE_DECLARE(Native_RTC_SetAlarm___STATIC__VOID__U1__U1__U1__U1__U1__U1__U1);

    //--//

};

struct Library_Eclo_STM32F4_Eclo_STM32F4_System
{
    static const int FIELD_STATIC___hardwareSerial = 0;

    TINYCLR_NATIVE_DECLARE(NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Eclo_STM32F4;

#endif  //_ECLO_STM32F4_H_
