//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Eclo_Hardware.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Eclo_Hardware_Eclo_Hardware_RTC::Native_RTC_Init___STATIC__VOID__U1__BOOLEAN,
    Library_Eclo_Hardware_Eclo_Hardware_RTC::Native_RTC_GetDateTime___STATIC__VOID__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1,
    Library_Eclo_Hardware_Eclo_Hardware_RTC::Native_RTC_SetDateTime___STATIC__VOID__U1__U1__U1__U1__U1__U1__U1,
    Library_Eclo_Hardware_Eclo_Hardware_RTC::Native_RTC_SetAlarm___STATIC__VOID__U1__U1__U1__U1__U1__U1__U1,
    NULL,
    Library_Eclo_Hardware_Eclo_Hardware_System::NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Eclo_Hardware =
{
    "Eclo.Hardware", 
    0x8481B92F,
    method_lookup
};

